name: outer_server # inner_server,outer_server
inner_server: # frpc的ini配置
    ssh_53: # 项目的ini配置
        RegisterAddress: tcp://0.0.0.0:9091 # 外网服务器对内网服务器的地址（这里填写外网服务器的InnerServerAddress）
        ProxyAddress: tcp://0.0.0.0:8080 # 本地目标服务
        AuthKey: 7000 # 连接授权码（内外网必须保持一致，长度不能超过32个字符）
        MaxFreeConn: 7000 # 最大空闲连接数，并发数高时可适当增大该参数
outer_server: # frps的ini配置
    ssh_53: # 项目的配置
        InnerServerAddress: tcp://0.0.0.0:9090 # 内网服务监听地址，内网服务器收到外网服务器通知后，会发起到该端口的连接用于处理客户端的请求
        OuterServerAddress: unix:///var/run/transponderouter.sock # 外部服务监听地址，用于对客户端提供服务,linux建议使用unix:///var/run/transponderouter.sock unix套接字的网络模式
        AuthKey: 7000 # 连接授权码（内外网必须保持一致，长度不能超过32个字符）
    # web_53: # 项目的ini配置
    #     common:
    #         bind_port: 7001
    #         vhost_http_port: 8001